[2022-09-28T21:42:19.351+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: preparing_motor_data_for_processing.call_ssh_task manual__2022-09-28T21:42:18.455758+00:00 [queued]>
[2022-09-28T21:42:19.358+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: preparing_motor_data_for_processing.call_ssh_task manual__2022-09-28T21:42:18.455758+00:00 [queued]>
[2022-09-28T21:42:19.360+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-28T21:42:19.361+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-28T21:42:19.362+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-28T21:42:19.371+0000] {taskinstance.py:1389} INFO - Executing <Task(SSHOperator): call_ssh_task> on 2022-09-28 21:42:18.455758+00:00
[2022-09-28T21:42:19.376+0000] {standard_task_runner.py:52} INFO - Started process 5264 to run task
[2022-09-28T21:42:19.379+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'preparing_motor_data_for_processing', 'call_ssh_task', 'manual__2022-09-28T21:42:18.455758+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/preparing_motor_data_for_processing.py', '--cfg-path', '/tmp/tmpbmh8h_te', '--error-file', '/tmp/tmpj1a2al9v']
[2022-09-28T21:42:19.388+0000] {standard_task_runner.py:80} INFO - Job 45: Subtask call_ssh_task
[2022-09-28T21:42:19.444+0000] {task_command.py:371} INFO - Running <TaskInstance: preparing_motor_data_for_processing.call_ssh_task manual__2022-09-28T21:42:18.455758+00:00 [running]> on host 3431a65fe7cb
[2022-09-28T21:42:19.494+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jsanchez
AIRFLOW_CTX_DAG_ID=preparing_motor_data_for_processing
AIRFLOW_CTX_TASK_ID=call_ssh_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-28T21:42:18.455758+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-28T21:42:18.455758+00:00
[2022-09-28T21:42:19.495+0000] {ssh.py:136} INFO - Creating ssh_client
[2022-09-28T21:42:19.496+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2022-09-28T21:42:19.503+0000] {base.py:68} INFO - Using connection ID 'qa_ai_app1' for task execution.
[2022-09-28T21:42:19.510+0000] {ssh.py:287} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2022-09-28T21:42:19.914+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2022-09-28T21:42:20.354+0000] {transport.py:1874} INFO - Authentication (publickey) successful!
[2022-09-28T21:42:20.355+0000] {ssh.py:464} INFO - Running command: pwd | ls -tr | touch file_name
[2022-09-28T21:42:21.200+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=preparing_motor_data_for_processing, task_id=call_ssh_task, execution_date=20220928T214218, start_date=20220928T214219, end_date=20220928T214221
[2022-09-28T21:42:21.246+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-28T21:42:21.269+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
