[2022-09-21T22:20:12.890+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.insert_pet_table manual__2022-09-21T22:19:53.096618+00:00 [queued]>
[2022-09-21T22:20:12.916+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.insert_pet_table manual__2022-09-21T22:19:53.096618+00:00 [queued]>
[2022-09-21T22:20:12.920+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T22:20:12.921+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-21T22:20:12.922+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T22:20:12.939+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_pet_table> on 2022-09-21 22:19:53.096618+00:00
[2022-09-21T22:20:12.946+0000] {standard_task_runner.py:52} INFO - Started process 62990 to run task
[2022-09-21T22:20:12.949+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag_example', 'insert_pet_table', 'manual__2022-09-21T22:19:53.096618+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_demo.py', '--cfg-path', '/tmp/tmpyy38aud5', '--error-file', '/tmp/tmpw0qvuyah']
[2022-09-21T22:20:12.951+0000] {standard_task_runner.py:80} INFO - Job 14: Subtask insert_pet_table
[2022-09-21T22:20:13.014+0000] {task_command.py:371} INFO - Running <TaskInstance: postgres_operator_dag_example.insert_pet_table manual__2022-09-21T22:19:53.096618+00:00 [running]> on host 49fa11dd9034
[2022-09-21T22:20:13.070+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jsanchez
AIRFLOW_CTX_DAG_ID=postgres_operator_dag_example
AIRFLOW_CTX_TASK_ID=insert_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-21T22:19:53.096618+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-21T22:19:53.096618+00:00
[2022-09-21T22:20:13.079+0000] {base.py:68} INFO - Using connection ID 'qa_ai_external_db' for task execution.
[2022-09-21T22:20:13.693+0000] {sql.py:315} INFO - Running statement: INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne'), parameters: None
[2022-09-21T22:20:13.898+0000] {sql.py:324} INFO - Rows affected: 1
[2022-09-21T22:20:14.045+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag_example, task_id=insert_pet_table, execution_date=20220921T221953, start_date=20220921T222012, end_date=20220921T222014
[2022-09-21T22:20:14.095+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-21T22:20:14.122+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
